## Recommender System
#### 1)Basic recommender system using M.F
#### 2)Using a library Spotlight

In [1]:
import numpy as np
import pandas as pd

In [2]:
!curl -O http://files.grouplens.org/datasets/movielens/ml-100k.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4808k  100 4808k    0     0   810k      0  0:00:05  0:00:05 --:--:-- 1288k


In [3]:
!unzip ml-100k.zip
!cd ml-100k/

Archive:  ml-100k.zip
   creating: ml-100k/
  inflating: ml-100k/allbut.pl       
  inflating: ml-100k/mku.sh          
  inflating: ml-100k/README          
  inflating: ml-100k/u.data          
  inflating: ml-100k/u.genre         
  inflating: ml-100k/u.info          
  inflating: ml-100k/u.item          
  inflating: ml-100k/u.occupation    
  inflating: ml-100k/u.user          
  inflating: ml-100k/u1.base         
  inflating: ml-100k/u1.test         
  inflating: ml-100k/u2.base         
  inflating: ml-100k/u2.test         
  inflating: ml-100k/u3.base         
  inflating: ml-100k/u3.test         
  inflating: ml-100k/u4.base         
  inflating: ml-100k/u4.test         
  inflating: ml-100k/u5.base         
  inflating: ml-100k/u5.test         
  inflating: ml-100k/ua.base         
  inflating: ml-100k/ua.test         
  inflating: ml-100k/ub.base         
  inflating: ml-100k/ub.test         


In [5]:
names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('ml-100k/u.data', sep='\t', names=names)
df.head()


user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [26]:
rating_matrix =pd.pivot_table(df,values='rating',columns='item_id',index='user_id').fillna(0)
rating_matrix.head(10)

item_id  1     2     3     4     5     6     7     8     9     10    ...   \
user_id                                                              ...    
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...    
2         4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...    
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
5         4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    
6         4.0   0.0   0.0   0.0   0.0   0.0   2.0   4.0   4.0   0.0  ...    
7         0.0   0.0   0.0   5.0   0.0   0.0   5.0   5.0   5.0   4.0  ...    
8         0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   0.0  ...    
9         0.0   0.0   0.0   0.0   0.0   5.0   4.0   0.0   0.0   0.0  ...    
10        4.0   0.0   0.0   4.0   0.0   0.0   4.0   0.0   4.0   0.0  ...    

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
8         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
9         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
10        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[10 rows x 1682 columns]

### Converting the above matrix to an array

In [28]:
rating_matrix = np.array(rating_matrix,dtype=np.float32)

In [36]:
#seeking fot nonzero indices for for a particular row
rating_matrix[1, :].nonzero()

(array([  0,   9,  12,  13,  18,  24,  49,  99, 110, 126, 236, 241, 250,
        254, 256, 257, 268, 271, 272, 273, 274, 275, 276, 277, 278, 279,
        280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,
        293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305,
        306, 307, 308, 309, 310, 311, 312, 313, 314, 315]),)

In [63]:
# this will get 25% of ratings for a user
np.random.choice(rating_matrix[1, :].nonzero()[0],size=int(len(rating_matrix[1, :].nonzero()[0])*0.25))

array([280, 276, 254, 314, 278,  12,  12, 305, 314, 282, 299, 256, 257,
       281,  12])

In [64]:
from tqdm import tqdm
train = rating_matrix.copy()
test = np.zeros(rating_matrix.shape)
for i in tqdm(range(len(rating_matrix))): 
    non_zero_ind = np.random.choice(rating_matrix[1, :].nonzero()[0],size=int(len(rating_matrix[1, :].nonzero()[0])*0.25))
    test[i,non_zero_ind]=rating_matrix[i,non_zero_ind]
    train[i,non_zero_ind]=0

100%|██████████| 943/943 [00:00<00:00, 12294.81it/s]


In [65]:
df.user_id.value_counts()[:5]

405    737
655    685
13     636
450    540
276    518
Name: user_id, dtype: int64

In [66]:
np.random.choice(rating_matrix[1, :].nonzero()[0],size=int(len(rating_matrix[1, :].nonzero()[0])*0.25))

array([297,  18, 289, 301, 276, 285,   0, 304, 110, 282, 310, 303, 297,
       309, 312])

In [67]:
df.item_id.value_counts()[:5]

50     583
258    509
100    508
181    507
294    485
Name: item_id, dtype: int64

### Now we have a complete dataset prepared,Its time to Apply matrix factorization

What is MF?

###### In the mathematical discipline of linear algebra, a matrix decomposition or matrix factorization is a factorization of a matrix into a product of matrices.<br> There are many different matrix decompositions; each finds use among a particular class of problems.

C : - i have taken the code of matrix factorization from below link 

https://gist.githubusercontent.com/EthanRosenthal/a0816d8fea4394baf732/raw/63cbbfd7a05cd49a0c0490c6d6312a3b6ad456da/ExplicitMF_ALS.py

In [79]:
class ExplicitMF():
    def __init__(self, 
                 ratings,
                 n_factors=40,
                 learning='sgd',
                 item_fact_reg=0.0, 
                 user_fact_reg=0.0,
                 item_bias_reg=0.0,
                 user_bias_reg=0.0,
                 verbose=False):
        """
        Train a matrix factorization model to predict empty 
        entries in a matrix. The terminology assumes a 
        ratings matrix which is ~ user x item
        
        Params
        ======
        ratings : (ndarray)
            User x Item matrix with corresponding ratings
        
        n_factors : (int)
            Number of latent factors to use in matrix 
            factorization model
        learning : (str)
            Method of optimization. Options include 
            'sgd' or 'als'.
        
        item_fact_reg : (float)
            Regularization term for item latent factors
        
        user_fact_reg : (float)
            Regularization term for user latent factors
            
        item_bias_reg : (float)
            Regularization term for item biases
        
        user_bias_reg : (float)
            Regularization term for user biases
        
        verbose : (bool)
            Whether or not to printout training progress
        """
        
        self.ratings = ratings
        self.n_users, self.n_items = ratings.shape
        self.n_factors = n_factors
        self.item_fact_reg = item_fact_reg
        self.user_fact_reg = user_fact_reg
        self.item_bias_reg = item_bias_reg
        self.user_bias_reg = user_bias_reg
        self.learning = learning
        if self.learning == 'sgd':
            self.sample_row, self.sample_col = self.ratings.nonzero()
            self.n_samples = len(self.sample_row)
        self._v = verbose

    def als_step(self,
                 latent_vectors,
                 fixed_vecs,
                 ratings,
                 _lambda,
                 type='user'):
        """
        One of the two ALS steps. Solve for the latent vectors
        specified by type.
        """
        if type == 'user':
            # Precompute
            YTY = fixed_vecs.T.dot(fixed_vecs)
            lambdaI = np.eye(YTY.shape[0]) * _lambda

            for u in xrange(latent_vectors.shape[0]):
                latent_vectors[u, :] = solve((YTY + lambdaI), 
                                             ratings[u, :].dot(fixed_vecs))
        elif type == 'item':
            # Precompute
            XTX = fixed_vecs.T.dot(fixed_vecs)
            lambdaI = np.eye(XTX.shape[0]) * _lambda
            
            for i in xrange(latent_vectors.shape[0]):
                latent_vectors[i, :] = solve((XTX + lambdaI), 
                                             ratings[:, i].T.dot(fixed_vecs))
        return latent_vectors

    def train(self, n_iter=10, learning_rate=0.1):
        """ Train model for n_iter iterations from scratch."""
        # initialize latent vectors        
        self.user_vecs = np.random.normal(scale=1./self.n_factors,\
                                          size=(self.n_users, self.n_factors))
        self.item_vecs = np.random.normal(scale=1./self.n_factors,
                                          size=(self.n_items, self.n_factors))
        
        if self.learning == 'als':
            self.partial_train(n_iter)
        elif self.learning == 'sgd':
            self.learning_rate = learning_rate
            self.user_bias = np.zeros(self.n_users)
            self.item_bias = np.zeros(self.n_items)
            self.global_bias = np.mean(self.ratings[np.where(self.ratings != 0)])
            self.partial_train(n_iter)
    
    
    def partial_train(self, n_iter):
        """ 
        Train model for n_iter iterations. Can be 
        called multiple times for further training.
        """
        ctr = 1
        while ctr <= n_iter:
            if ctr % 10 == 0 and self._v:
                print '\tcurrent iteration: {}'.format(ctr)
            if self.learning == 'als':
                self.user_vecs = self.als_step(self.user_vecs, 
                                               self.item_vecs, 
                                               self.ratings, 
                                               self.user_fact_reg, 
                                               type='user')
                self.item_vecs = self.als_step(self.item_vecs, 
                                               self.user_vecs, 
                                               self.ratings, 
                                               self.item_fact_reg, 
                                               type='item')
            elif self.learning == 'sgd':
                self.training_indices = np.arange(self.n_samples)
                np.random.shuffle(self.training_indices)
                self.sgd()
            ctr += 1

    def sgd(self):
        for idx in self.training_indices:
            u = self.sample_row[idx]
            i = self.sample_col[idx]
            prediction = self.predict(u, i)
            e = (self.ratings[u,i] - prediction) # error
            
            # Update biases
            self.user_bias[u] += self.learning_rate * \
                                (e - self.user_bias_reg * self.user_bias[u])
            self.item_bias[i] += self.learning_rate * \
                                (e - self.item_bias_reg * self.item_bias[i])
            
            #Update latent factors
            self.user_vecs[u, :] += self.learning_rate * \
                                    (e * self.item_vecs[i, :] - \
                                     self.user_fact_reg * self.user_vecs[u,:])
            self.item_vecs[i, :] += self.learning_rate * \
                                    (e * self.user_vecs[u, :] - \
                                     self.item_fact_reg * self.item_vecs[i,:])
    def predict(self, u, i):
        """ Single user and item prediction."""
        if self.learning == 'als':
            return self.user_vecs[u, :].dot(self.item_vecs[i, :].T)
        elif self.learning == 'sgd':
            prediction = self.global_bias + self.user_bias[u] + self.item_bias[i]
            prediction += self.user_vecs[u, :].dot(self.item_vecs[i, :].T)
            return prediction
    
    def predict_all(self):
        """ Predict ratings for every user and item."""
        predictions = np.zeros((self.user_vecs.shape[0], 
                                self.item_vecs.shape[0]))
        for u in xrange(self.user_vecs.shape[0]):
            for i in xrange(self.item_vecs.shape[0]):
                predictions[u, i] = self.predict(u, i)
                
        return predictions
    
    def calculate_learning_curve(self, iter_array, test, learning_rate=0.1):
        """
        Keep track of MSE as a function of training iterations.
        
        Params
        ======
        iter_array : (list)
            List of numbers of iterations to train for each step of 
            the learning curve. e.g. [1, 5, 10, 20]
        test : (2D ndarray)
            Testing dataset (assumed to be user x item).
        
        The function creates two new class attributes:
        
        train_mse : (list)
            Training data MSE values for each value of iter_array
        test_mse : (list)
            Test data MSE values for each value of iter_array
        """
        iter_array.sort()
        self.train_mse =[]
        self.test_mse = []
        iter_diff = 0
        for (i, n_iter) in enumerate(iter_array):
            if self._v:
                print 'Iteration: {}'.format(n_iter)
            if i == 0:
                self.train(n_iter - iter_diff, learning_rate)
            else:
                self.partial_train(n_iter - iter_diff)

            predictions = self.predict_all()

            self.train_mse += [get_mse(predictions, self.ratings)]
            self.test_mse += [get_mse(predictions, test)]
            if self._v:
                print 'Train mse: ' + str(self.train_mse[-1])
                print 'Test mse: ' + str(self.test_mse[-1])
            iter_diff = n_iter

In [80]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)


In [83]:
MF_SGD = ExplicitMF(train, 40, learning='sgd', verbose=True,user_bias_reg=0.001,user_fact_reg=0.001)
iter_array = [100]
MF_SGD.calculate_learning_curve(iter_array, test, learning_rate=0.001)

Iteration: 100
	current iteration: 10
	current iteration: 20
	current iteration: 30
	current iteration: 40
	current iteration: 50
	current iteration: 60
	current iteration: 70
	current iteration: 80
	current iteration: 90
	current iteration: 100
Train mse: 0.75212592578
Test mse: 0.858176057909


In [84]:
MF_SGD.predict_all()

array([[ 3.88769711,  3.28424166,  3.16969442, ...,  3.30172906,
         3.43990133,  3.41537192],
       [ 3.92259853,  3.34744285,  3.12803526, ...,  3.36876411,
         3.48892768,  3.45347251],
       [ 3.27989385,  2.73310127,  2.56267407, ...,  2.808713  ,
         2.91929342,  2.8764967 ],
       ..., 
       [ 4.15219642,  3.62578233,  3.39519047, ...,  3.6242259 ,
         3.74556963,  3.7048088 ],
       [ 4.36833021,  3.79683035,  3.54317005, ...,  3.76663469,
         3.90245888,  3.85319409],
       [ 3.84577806,  3.2094572 ,  2.98950861, ...,  3.19859554,
         3.32257895,  3.2878383 ]])

In [107]:
import numpy as np

from spotlight.datasets.movielens import get_movielens_dataset

dataset = get_movielens_dataset(variant='100K')
print(dataset)

<Interactions dataset (944 users x 1683 items x 100000 interactions)>


## Spotlight package for Matrix Factorization

In [121]:
import torch

from spotlight.factorization.explicit import ExplicitFactorizationModel

model = ExplicitFactorizationModel(loss='regression',
                                   embedding_dim=256,  # latent dimensionality
                                   n_iter=10,  # number of epochs of training
                                   batch_size=512,  # minibatch size
                                   l2=1e-9,  # strength of L2 regularization
                                   learning_rate=1e-3)

In [122]:
from spotlight.cross_validation import  random_train_test_split
train,test = random_train_test_split(dataset)

In [123]:
model.fit(train,verbose=True)

Epoch 0: loss 9.75738052502
Epoch 1: loss 1.35926692767
Epoch 2: loss 0.950820614198
Epoch 3: loss 0.894138938682
Epoch 4: loss 0.866310629116
Epoch 5: loss 0.843947508533
Epoch 6: loss 0.819643738164
Epoch 7: loss 0.796120296618
Epoch 8: loss 0.773396581981
Epoch 9: loss 0.747750704835


In [124]:
from spotlight.evaluation import rmse_score
rmse_score(model,test)

0.92347807